import { createHash } from 'node:crypto';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

/*
 * Writes dist/sw.js, the service worker that lets the app open with no
 * connection.
 *
 * Generated at build time rather than kept in public/, because it needs the
 * exact list of files this build produced (their names carry content hashes).
 * The version is a hash of that list, so every build that changes a file
 * installs a fresh worker and drops the old cache.
 */
function serviceWorker() {
  return {
    name: 'edupyramids-service-worker',
    apply: 'build',
    generateBundle(_, bundle) {
      const files = Object.keys(bundle).filter((f) => !f.endsWith('.map'));
      const shell = ['/', ...files.map((f) => `/${f}`),
        '/edupyramids-logo.png', '/favicon.svg', '/favicon.ico',
        '/icon-192.png', '/icon-512.png', '/manifest.webmanifest'];
      const version = createHash('sha256').update(shell.join('|')).digest('hex').slice(0, 12);

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: `/* Generated by vite.config.js. Do not edit. */
const CACHE = 'edupyramids-${version}';
const SHELL = ${JSON.stringify(shell)};

// Keep the app itself, so it opens with no network.
self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

// Drop the caches of older builds.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('edupyramids-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // The typefaces come from Google Fonts. Keep the first copy seen, so
  // offline pages still look like the app.
  if (request.method === 'GET' && /(^|\\.)fonts\\.(googleapis|gstatic)\\.com$/.test(url.hostname)) {
    event.respondWith(
      caches.match(request).then((hit) => hit || fetch(request).then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(request, copy));
        return res;
      })),
    );
    return;
  }

  // The API is the page's business: it keeps its own offline copies and queue.
  if (request.method !== 'GET' || url.origin !== self.location.origin || url.pathname.startsWith('/api/')) return;

  // Pages: the network first, so a deploy shows up at once; the saved app when offline.
  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(() => caches.match('/')));
    return;
  }

  // Files named by their content never change, so the saved copy is always right.
  event.respondWith(
    caches.match(request).then((hit) => hit || fetch(request).then((res) => {
      if (res.ok) {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(request, copy));
      }
      return res;
    })),
  );
});
`,
      });
    },
  };
}

export default defineConfig({
  plugins: [react(), serviceWorker()],
  server: {
    port: 5173,
    // The API sets its CORS origin from FRONTEND_URL. If this port moves, that
    // value has to move with it or every request is blocked.
    strictPort: true,
  },
});
