#!/usr/bin/env python3
"""Convert the client's MySQL dump into PostgreSQL, for a read-only mirror.

The school database is a source, never a destination. Nothing this project owns
is ever written into it: EduPyramids keeps its own tables in its own database,
and reads students and accounts from this mirror.

Only the tables the app actually reads are converted. The rest of the dump —
sessions, OTP hashes, permissions, admin logs — is left behind on purpose. It is
personal data with no use here, and the safest copy of it is the one that was
never made.

    python3 scripts/convert-school-dump.py <dump.sql> <out.sql> [--limit N]
"""
import re
import sys

# Only these. See the note above about everything else.
TABLES = [
    'common_level',
    'locations_state', 'locations_district', 'locations_city',
    'stp_training_organization', 'stp_training_academiccenter',
    'stp_training_academicsession', 'stp_training_grade', 'stp_training_section',
    'stp_training_category', 'stp_training_batch',
    # Roles: school sign-in reads them from here, so without it every school
    # login fails. accounts_profile (phone, date of birth, address) is left out:
    # nothing here reads it.
    'accounts_user', 'accounts_userrolemapping',
    'stp_training_student', 'stp_training_studentenrollment',
    # Who is on which course (Python), per the client's schema.
    'stp_training_fosscategory', 'stp_training_training', 'stp_training_trainingenrollment',
]

TYPES = [
    (re.compile(r'\bbigint\(\d+\)\s+unsigned', re.I), 'bigint'),
    (re.compile(r'\bbigint\(\d+\)', re.I), 'bigint'),
    (re.compile(r'\bint\(\d+\)\s+unsigned', re.I), 'integer'),
    (re.compile(r'\bint\(\d+\)', re.I), 'integer'),
    (re.compile(r'\bsmallint\(\d+\)\s+unsigned', re.I), 'integer'),
    (re.compile(r'\bsmallint\(\d+\)', re.I), 'smallint'),
    # tinyint(1) is a boolean in Django, but the dump writes 0 and 1. smallint
    # keeps the load simple; the API maps it when it reads.
    (re.compile(r'\btinyint\(\d+\)', re.I), 'smallint'),
    (re.compile(r'\bdatetime\(\d+\)', re.I), 'timestamp'),
    (re.compile(r'\bdatetime\b', re.I), 'timestamp'),
    (re.compile(r'\blongtext\b', re.I), 'text'),
    (re.compile(r'\bdouble\b', re.I), 'double precision'),
    (re.compile(r'\bdecimal\(', re.I), 'numeric('),
]

INDEXES = """
CREATE INDEX IF NOT EXISTS school_user_email ON accounts_user (lower(email) text_pattern_ops);
CREATE INDEX IF NOT EXISTS school_user_username ON accounts_user (lower(username) text_pattern_ops);
CREATE INDEX IF NOT EXISTS school_user_spk ON accounts_user (spk_user_id);
CREATE INDEX IF NOT EXISTS school_role_user ON accounts_userrolemapping (user_id);
CREATE INDEX IF NOT EXISTS school_student_user ON stp_training_student (user_id);
CREATE INDEX IF NOT EXISTS school_enrol_student ON stp_training_studentenrollment (student_id);
CREATE INDEX IF NOT EXISTS school_enrol_batch ON stp_training_studentenrollment (batch_id);
ANALYZE;
"""

DROP_LINE = re.compile(r'^\s*(KEY|UNIQUE KEY|CONSTRAINT|FULLTEXT KEY|INDEX)\b', re.I)


def convert_create(lines):
    out = []
    for line in lines:
        if DROP_LINE.match(line):
            continue
        line = line.replace('`', '"')
        line = re.sub(r'\s+AUTO_INCREMENT\b', '', line, flags=re.I)
        line = re.sub(r'\s+COLLATE\s+\S+', '', line, flags=re.I)
        line = re.sub(r'\s+CHARACTER SET\s+\S+', '', line, flags=re.I)
        # CHECK constraints reference quoted identifiers and add nothing to a
        # read-only mirror.
        line = re.sub(r'\s+CHECK\s*\(.*?\)', '', line, flags=re.I)
        line = re.sub(r'\)\s*ENGINE=.*?;', ');', line, flags=re.I)
        for pattern, replacement in TYPES:
            line = pattern.sub(replacement, line)
        out.append(line)

    # A dropped KEY may leave a dangling comma before the closing bracket.
    text = ''.join(out)
    text = re.sub(r',(\s*)\)\s*;', r'\1);', text)
    return text


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(2)

    src, dst = sys.argv[1], sys.argv[2]
    limit = None
    if '--limit' in sys.argv:
        limit = int(sys.argv[sys.argv.index('--limit') + 1])

    wanted = set(TABLES)
    counts = {t: 0 for t in TABLES}

    with open(src, encoding='utf8', errors='replace') as f, \
            open(dst, 'w', encoding='utf8') as out:
        out.write('-- Generated by scripts/convert-school-dump.py. Do not edit.\n')
        out.write('-- A read-only mirror of the client database. Never written to.\n')
        # The dump uses MySQL backslash escapes inside string literals.
        out.write("SET standard_conforming_strings = off;\n")
        out.write("SET client_min_messages = warning;\n\n")

        table = None
        mode = None
        buffer = []
        emitting = False

        for line in f:
            if line.startswith('DROP TABLE'):
                continue

            if line.startswith('CREATE TABLE `'):
                table = line.split('`')[1]
                mode = 'create' if table in wanted else None
                buffer = [line] if mode else []
                continue

            if mode == 'create':
                buffer.append(line)
                if line.startswith(')'):
                    out.write(convert_create(buffer))
                    out.write('\n')
                    mode = None
                continue

            if line.startswith('INSERT INTO `'):
                table = line.split('`')[1]
                if table in wanted:
                    mode = 'insert'
                    emitting = True
                    out.write(line.replace('`', '"'))
                else:
                    mode = None
                continue

            if mode == 'insert':
                if limit is not None and counts[table] >= limit:
                    # Close the statement early and skip the rest of the block.
                    if emitting:
                        out.write(';\n')
                        emitting = False
                    if line.rstrip().endswith(';'):
                        mode = None
                    continue

                if line.startswith('('):
                    counts[table] += 1
                out.write(line)
                if line.rstrip().endswith(';'):
                    mode = None
                    emitting = False

        # The dump's own KEY lines are dropped with the MySQL syntax, so add
        # back the indexes the app's lookups use. Without them a sign-in scans
        # a million accounts.
        out.write('\n' + INDEXES)

    print('converted:')
    for t in TABLES:
        print(f'  {t:34s} {counts[t]:>9,} rows')


if __name__ == '__main__':
    main()
